## security 설정
github:
  accessTokenUrl: https://github.com/login/oauth/access_token
  clientId : bdd909bfff2137535182
  clientSecret : 5de5688e0541838556d68954769ed7990ec54fac
  redirectUrl : http://localhost:8080/login/oauth2/code/github
  userEmailRequestUrl : https://api.github.com/user/emails
