spring:
  profiles:
    active: dev
    include: oauth

# logging 설정
logging:
  level:
    root: INFO
    sql: trace
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS,Asia/Seoul} [%thread] %-5level %logger{36}.%M - %msg%n"
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS,Asia/Seoul} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
  file:
    name: logs/dev_log.log
---
spring:
  profiles: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/issue04?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useLegacyDatetimeCode=false
    username: issue04
    password: issue04
    initialization-mode: always
    hikari:
      maximum-pool-size: 10
  flyway:
    clean-on-validation-error: true
    url: jdbc:mysql://localhost:3306/issue04?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useLegacyDatetimeCode=false
    user: issue04
    password: issue04
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 0
---
cloud:
  aws:
    credentials:
      accessKey: 액세스
      secretKey: 시크릿 키
    s3:
      bucket: issue-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false