
name: CI

env:
  PROJECT_NAME: Jack_codedeploy

on:
  push:
    branches: deploy


jobs:
  
  deploy:
    name: DEPLOY
    runs-on: ubuntu-18.04
    env:
      working-directory: ./BE

    steps:
      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0
        
        
      - name: Checkout
        uses: actions/checkout@v2

        
      - name: Run a one-line script
        run: echo Start Deploy.

        
      - name: Run a multi-line script
        run: |
          echo We love Honux,
          echo CodeSquad 2020 Java Backend.
          
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v2
         
        
      - name: Grant execute permission for gradlew
        run: |
          echo $(pwd)
          chmod +x gradlew
        shell: bash
        working-directory: ./BE
        
      
        
      - name: Build with Gradle
        run: |
          ./gradlew build -x test
        shell: bash
        working-directory: ./BE

      
      - name: Make zip file
        run: |
          echo $(pwd)
          zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash
        working-directory: ./BE
      
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      #- name: Setup tmate session
       # uses: mxschmitt/action-tmate@v2
      
        
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://issuetracker-deploy/$PROJECT_NAME/$GITHUB_SHA.zip
        working-directory: ./BE

        
      - name: Code Deploy
        run: aws deploy create-deployment --application-name issueTracker-codedeploy --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name dev --s3-location bucket=issuetracker-deploy,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
